### ISSUE TITLE
minimal version of pandoc

### ISSUE THREAD

**Issue by setop** [chunqiuyiyu/inkval#2]
I first tested with pandoc 2.9.2.1, provided by Debian Bulleye. I had some glitch with the front matter still present in the generated HTML.

I upgraded to pandoc 2.16.2, last release on Github. Glitch disappeared.

I don't know exactly which version is required but a recent one ;)

It should be indicated in the readme.

**Comment by chunqiuyiyu** [comment]
Yes, you are right. I have updated tips of pandoc in the readme file.
